### ISSUE TITLE
na values troubleshooting

### ISSUE THREAD

**Issue by raetaylorburns** [resilienseas/resilienseas.github.io#3]
Hi @bbest !

Hope you're doing well. We are chugging away on our scripts, and have run up on a small issue in our gap analysis here: https://github.com/resilienseas/resilienseas.github.io/blob/772228eb30fe4c1939569230a9ffed8130879875/scripts/gapanalysis.R#L127.

The code runs fine, but we are calculating polygons for monitoring sites that may be nearshore or estuarine. Bio-Oracle recognizes this as a "not ocean" area, and therefore does not have an SST value associated with those locations. As a result, we get some really big blank spots on the visualization, which carries through our whole analysis. This makes it look like there are 0 values in places that we know have sea surface temperatures associated with them. 

I have tried to deal with this by writing an if statement to replace NA values with values from the nearest neighbor here: https://github.com/resilienseas/resilienseas.github.io/blob/772228eb30fe4c1939569230a9ffed8130879875/scripts/gapanalysis.R#L116-L124 but the statement does not work... I'm not even sure if this is the best way to solve the problem, and your insight would be super helpful!

Cheers,
Rae

**Comment by bbest** [comment]
Good try. Right idea. I googled "R raster fill NA" and found [raster - Fill the gaps using nearest neighbors](https://gis.stackexchange.com/questions/181011/fill-the-gaps-using-nearest-neighbors).

I went ahead and implemented this in a new `oatools` function [`lyr_to_tif()`](https://github.com/resilienseas/oatools/blob/11d1e943a776de6d0b2fc140a84c5e8d142b1e22/R/tools.R#L14-L72) which has two arguments set to their default values: `fill_na=TRUE`, `fill_window=3`. I left the documentation up to you.

Notice how I loaded the `oatools` package, which assumes you have resilienseas version of [`oatools`](https://github.com/resilienseas/oatools) loaded in the same folder as `resilienseas.github.io`:

https://github.com/resilienseas/resilienseas.github.io/blob/2ac69c38c16bcfc39ad6df6ce0c269cd494fab5c/scripts/gapanalysis.R#L14

Then I tested before/after adding the fill functionality:

https://github.com/resilienseas/resilienseas.github.io/blob/2ac69c38c16bcfc39ad6df6ce0c269cd494fab5c/scripts/gapanalysis.R#L49-L60

**Comment by bbest** [comment]
Hi @raetaylorburns, does what I did make sense? 

Please see these 2 comments on your additional commit to gapanalysis.R:
- https://github.com/resilienseas/resilienseas.github.io/commit/8927dece222e86d438eded5b02799a17b00399e6#r27331538

  ```r
  devtools::load_all(here("../oatools"))
  ```
- https://github.com/resilienseas/resilienseas.github.io/commit/8927dece222e86d438eded5b02799a17b00399e6#r27331628

  ```r
  fill.na<- function(polygonsstrange){
  ```

**Comment by raetaylorburns** [comment]
Hi @bbest! 

Sorry for the late reply - I was working on this Thursday/Friday but ran out of time and didn't want to circle back with more questions until I had spent some more time on it. That said, I do understand the part about storing oatools in the same folder as resilienseas.github.io and I thought I had it setup like that...but I am not sure I understand the fill_windows = 3 part of lyrtotif.

I also misunderstood that based off what you did I wouldn't have to redo the fill for every parameter. I hope I didn't take too many steps back from the help you gave us. I was getting this error: Error in .local(x, ...) : w must have uneven sides here: https://github.com/resilienseas/resilienseas.github.io/blob/8927dece222e86d438eded5b02799a17b00399e6/scripts/gapanalysis.R#L151 and I wasn't sure if this was something I messed up from the help you gave us on Thursday. 

In any case - sorry for the radio silence! I probably should have asked more questions on Friday instead of just messing up code you had written trying to understand it. I will go back to what you had sent me on Thursday and see if I can work from there... 

Thank you!
Rae

**Comment by raetaylorburns** [comment]
Hi @bbest !

I undid what I had done on Thursday/Friday, so the script is now almost as you left it  but I changed some variable names... However I am still getting the error message "Error in .local(x, ...) : w must have uneven sides" here: https://github.com/resilienseas/resilienseas.github.io/blob/8927dece222e86d438eded5b02799a17b00399e6/scripts/gapanalysis.R#L151

Is this something I messed up from your code? From the documentation it seems that focal() requires odd numbers of columns and rows... which our rasters are not. Any tips?

Thank you so much for your help!

Rae

**Comment by bbest** [comment]
Hi @raetaylorburns,

Yes, you're right that `focal()` requires an odd window size and now I see that I didn't properly account for how the `fill_window` affects the index `i` of the center value within the fill window, which is the cell to be checked for NA and if NA then replace with the average of its neighbors. 

In the solution [raster - Fill the gaps using nearest neighbors](https://gis.stackexchange.com/questions/181011/fill-the-gaps-using-nearest-neighbors), it is mentioned:

> If the window size increases the index value [i] needs to change as well (eg., for a 5x5 window the index would be 13).

Let's look at the indices for the focal window of these two window sizes, and then call x's after encountering the center cell:

```
# fill_window:3 -> i:5
1,2,3,
4,5,x
x,x,x
        
# fill_window:5 -> i:13
1 , 2, 3, 4, 5
6 , 7, 8, 9,10
11,12,13, x, x
 x, x, x, x, x
 x, x, x, x, x
```

So `i` should be `fill_window` * half the rows (rounded down), plus `fill_window` * half the columns (rounded up; to account for middle row):

```r
i <- (fill_window * floor(fill_window / 2))  + ceiling(fill_window / 2)
```

I fixed the `oatools::lyr_to_tif()` function at https://github.com/resilienseas/oatools/blob/a3c7f7151b84063e487cc20339f030e0a4557505/R/tools.R#L54-L63.

[Aside: Notice how you can uncomment `#browser()` to pause execution and inspect values after calling the function `lyr_to_tif()`. (This only practically works if you use `devtools::load_all(here("../oatools"))` to load oatools, otherwise you have to git commit&push oatools then reinstall package which is silly). Be sure to recomment before pushing oatools back to Github.]

Let's see how the difference in number of NAs with and without filling (`fill_window=11`) affects things here:

https://github.com/resilienseas/resilienseas.github.io/blob/54c75d08c3d8f33beb1585436cde691b0c495e29/scripts/gapanalysis.R#L51-L71

So without the fill, we have 11,835 NAs:
  
  ![image](https://user-images.githubusercontent.com/2837257/35824142-c418c1e8-0a66-11e8-9adc-f1c15af539f4.png)
  
And with the fill of window 11, we have 9,791 NAs:
  
  ![image](https://user-images.githubusercontent.com/2837257/35824160-d6baa6cc-0a66-11e8-9e88-75272d156ef0.png)

You might want to inspect these one on top of the other, since the non-NA values in the original should be the same as the filled in version.

**Comment by raetaylorburns** [comment]
Hi @bbest ! Thank you for the great explanation about fill_windows - that makes sense to me now. Thank you so much for your help!  The fill window of 11 solves the problem of entire polygons of NA values spreading into the ocean, so that works well. I am pretty I got it all sorted out... I changed the equations for the "differences" so that it finds the difference between the rasterized polygons made from the na fill tifs, and the regular rasters from the no_fill tiffs. I think this solves the problem! Many many thanks!
